// Generated by gencpp from file qt_ground_station/ControlParameter.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_CONTROLPARAMETER_H
#define QT_GROUND_STATION_MESSAGE_CONTROLPARAMETER_H

#include <ros/service_traits.h>


#include <qt_ground_station/ControlParameterRequest.h>
#include <qt_ground_station/ControlParameterResponse.h>


namespace qt_ground_station
{

struct ControlParameter
{

typedef ControlParameterRequest Request;
typedef ControlParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlParameter
} // namespace qt_ground_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_ground_station::ControlParameter > {
  static const char* value()
  {
    return "6564e4eb6ec261394b295cdd4e73b53a";
  }

  static const char* value(const ::qt_ground_station::ControlParameter&) { return value(); }
};

template<>
struct DataType< ::qt_ground_station::ControlParameter > {
  static const char* value()
  {
    return "qt_ground_station/ControlParameter";
  }

  static const char* value(const ::qt_ground_station::ControlParameter&) { return value(); }
};


// service_traits::MD5Sum< ::qt_ground_station::ControlParameterRequest> should match
// service_traits::MD5Sum< ::qt_ground_station::ControlParameter >
template<>
struct MD5Sum< ::qt_ground_station::ControlParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::ControlParameter >::value();
  }
  static const char* value(const ::qt_ground_station::ControlParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::ControlParameterRequest> should match
// service_traits::DataType< ::qt_ground_station::ControlParameter >
template<>
struct DataType< ::qt_ground_station::ControlParameterRequest>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::ControlParameter >::value();
  }
  static const char* value(const ::qt_ground_station::ControlParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_ground_station::ControlParameterResponse> should match
// service_traits::MD5Sum< ::qt_ground_station::ControlParameter >
template<>
struct MD5Sum< ::qt_ground_station::ControlParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::ControlParameter >::value();
  }
  static const char* value(const ::qt_ground_station::ControlParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::ControlParameterResponse> should match
// service_traits::DataType< ::qt_ground_station::ControlParameter >
template<>
struct DataType< ::qt_ground_station::ControlParameterResponse>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::ControlParameter >::value();
  }
  static const char* value(const ::qt_ground_station::ControlParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_CONTROLPARAMETER_H
