// Generated by gencpp from file qt_ground_station/GeneralInfoResponse.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_GENERALINFORESPONSE_H
#define QT_GROUND_STATION_MESSAGE_GENERALINFORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_ground_station
{
template <class ContainerAllocator>
struct GeneralInfoResponse_
{
  typedef GeneralInfoResponse_<ContainerAllocator> Type;

  GeneralInfoResponse_()
    : oktostart(false)  {
    }
  GeneralInfoResponse_(const ContainerAllocator& _alloc)
    : oktostart(false)  {
  (void)_alloc;
    }



   typedef uint8_t _oktostart_type;
  _oktostart_type oktostart;





  typedef boost::shared_ptr< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GeneralInfoResponse_

typedef ::qt_ground_station::GeneralInfoResponse_<std::allocator<void> > GeneralInfoResponse;

typedef boost::shared_ptr< ::qt_ground_station::GeneralInfoResponse > GeneralInfoResponsePtr;
typedef boost::shared_ptr< ::qt_ground_station::GeneralInfoResponse const> GeneralInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator1> & lhs, const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.oktostart == rhs.oktostart;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator1> & lhs, const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_ground_station

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "860a691c70e14a4dcb7ec7957ddafcce";
  }

  static const char* value(const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x860a691c70e14a4dULL;
  static const uint64_t static_value2 = 0xcb7ec7957ddafcceULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_ground_station/GeneralInfoResponse";
  }

  static const char* value(const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool oktostart\n"
"\n"
;
  }

  static const char* value(const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.oktostart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeneralInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_ground_station::GeneralInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "oktostart: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.oktostart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_GENERALINFORESPONSE_H
