// Generated by gencpp from file qt_ground_station/GeneralInfo.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_GENERALINFO_H
#define QT_GROUND_STATION_MESSAGE_GENERALINFO_H

#include <ros/service_traits.h>


#include <qt_ground_station/GeneralInfoRequest.h>
#include <qt_ground_station/GeneralInfoResponse.h>


namespace qt_ground_station
{

struct GeneralInfo
{

typedef GeneralInfoRequest Request;
typedef GeneralInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GeneralInfo
} // namespace qt_ground_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_ground_station::GeneralInfo > {
  static const char* value()
  {
    return "f5411d5ea2241dbc1c5aa4c2c6403d8d";
  }

  static const char* value(const ::qt_ground_station::GeneralInfo&) { return value(); }
};

template<>
struct DataType< ::qt_ground_station::GeneralInfo > {
  static const char* value()
  {
    return "qt_ground_station/GeneralInfo";
  }

  static const char* value(const ::qt_ground_station::GeneralInfo&) { return value(); }
};


// service_traits::MD5Sum< ::qt_ground_station::GeneralInfoRequest> should match
// service_traits::MD5Sum< ::qt_ground_station::GeneralInfo >
template<>
struct MD5Sum< ::qt_ground_station::GeneralInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::GeneralInfo >::value();
  }
  static const char* value(const ::qt_ground_station::GeneralInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::GeneralInfoRequest> should match
// service_traits::DataType< ::qt_ground_station::GeneralInfo >
template<>
struct DataType< ::qt_ground_station::GeneralInfoRequest>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::GeneralInfo >::value();
  }
  static const char* value(const ::qt_ground_station::GeneralInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_ground_station::GeneralInfoResponse> should match
// service_traits::MD5Sum< ::qt_ground_station::GeneralInfo >
template<>
struct MD5Sum< ::qt_ground_station::GeneralInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::GeneralInfo >::value();
  }
  static const char* value(const ::qt_ground_station::GeneralInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::GeneralInfoResponse> should match
// service_traits::DataType< ::qt_ground_station::GeneralInfo >
template<>
struct DataType< ::qt_ground_station::GeneralInfoResponse>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::GeneralInfo >::value();
  }
  static const char* value(const ::qt_ground_station::GeneralInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_GENERALINFO_H
