// Generated by gencpp from file qt_ground_station/MultiPayloadAction.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_MULTIPAYLOADACTION_H
#define QT_GROUND_STATION_MESSAGE_MULTIPAYLOADACTION_H

#include <ros/service_traits.h>


#include <qt_ground_station/MultiPayloadActionRequest.h>
#include <qt_ground_station/MultiPayloadActionResponse.h>


namespace qt_ground_station
{

struct MultiPayloadAction
{

typedef MultiPayloadActionRequest Request;
typedef MultiPayloadActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultiPayloadAction
} // namespace qt_ground_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_ground_station::MultiPayloadAction > {
  static const char* value()
  {
    return "901dfe89bb4f4622133561aed17b3eb7";
  }

  static const char* value(const ::qt_ground_station::MultiPayloadAction&) { return value(); }
};

template<>
struct DataType< ::qt_ground_station::MultiPayloadAction > {
  static const char* value()
  {
    return "qt_ground_station/MultiPayloadAction";
  }

  static const char* value(const ::qt_ground_station::MultiPayloadAction&) { return value(); }
};


// service_traits::MD5Sum< ::qt_ground_station::MultiPayloadActionRequest> should match
// service_traits::MD5Sum< ::qt_ground_station::MultiPayloadAction >
template<>
struct MD5Sum< ::qt_ground_station::MultiPayloadActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::MultiPayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::MultiPayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::MultiPayloadActionRequest> should match
// service_traits::DataType< ::qt_ground_station::MultiPayloadAction >
template<>
struct DataType< ::qt_ground_station::MultiPayloadActionRequest>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::MultiPayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::MultiPayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_ground_station::MultiPayloadActionResponse> should match
// service_traits::MD5Sum< ::qt_ground_station::MultiPayloadAction >
template<>
struct MD5Sum< ::qt_ground_station::MultiPayloadActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::MultiPayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::MultiPayloadActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::MultiPayloadActionResponse> should match
// service_traits::DataType< ::qt_ground_station::MultiPayloadAction >
template<>
struct DataType< ::qt_ground_station::MultiPayloadActionResponse>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::MultiPayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::MultiPayloadActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_MULTIPAYLOADACTION_H
