// Generated by gencpp from file qt_ground_station/SetHome.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_SETHOME_H
#define QT_GROUND_STATION_MESSAGE_SETHOME_H

#include <ros/service_traits.h>


#include <qt_ground_station/SetHomeRequest.h>
#include <qt_ground_station/SetHomeResponse.h>


namespace qt_ground_station
{

struct SetHome
{

typedef SetHomeRequest Request;
typedef SetHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHome
} // namespace qt_ground_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_ground_station::SetHome > {
  static const char* value()
  {
    return "798e15e3d217d7b631c2305a881a5677";
  }

  static const char* value(const ::qt_ground_station::SetHome&) { return value(); }
};

template<>
struct DataType< ::qt_ground_station::SetHome > {
  static const char* value()
  {
    return "qt_ground_station/SetHome";
  }

  static const char* value(const ::qt_ground_station::SetHome&) { return value(); }
};


// service_traits::MD5Sum< ::qt_ground_station::SetHomeRequest> should match
// service_traits::MD5Sum< ::qt_ground_station::SetHome >
template<>
struct MD5Sum< ::qt_ground_station::SetHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::SetHome >::value();
  }
  static const char* value(const ::qt_ground_station::SetHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::SetHomeRequest> should match
// service_traits::DataType< ::qt_ground_station::SetHome >
template<>
struct DataType< ::qt_ground_station::SetHomeRequest>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::SetHome >::value();
  }
  static const char* value(const ::qt_ground_station::SetHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_ground_station::SetHomeResponse> should match
// service_traits::MD5Sum< ::qt_ground_station::SetHome >
template<>
struct MD5Sum< ::qt_ground_station::SetHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::SetHome >::value();
  }
  static const char* value(const ::qt_ground_station::SetHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::SetHomeResponse> should match
// service_traits::DataType< ::qt_ground_station::SetHome >
template<>
struct DataType< ::qt_ground_station::SetHomeResponse>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::SetHome >::value();
  }
  static const char* value(const ::qt_ground_station::SetHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_SETHOME_H
