// Generated by gencpp from file qt_ground_station/SetHomeResponse.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_SETHOMERESPONSE_H
#define QT_GROUND_STATION_MESSAGE_SETHOMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_ground_station
{
template <class ContainerAllocator>
struct SetHomeResponse_
{
  typedef SetHomeResponse_<ContainerAllocator> Type;

  SetHomeResponse_()
    : homeset_ok(false)  {
    }
  SetHomeResponse_(const ContainerAllocator& _alloc)
    : homeset_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _homeset_ok_type;
  _homeset_ok_type homeset_ok;





  typedef boost::shared_ptr< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetHomeResponse_

typedef ::qt_ground_station::SetHomeResponse_<std::allocator<void> > SetHomeResponse;

typedef boost::shared_ptr< ::qt_ground_station::SetHomeResponse > SetHomeResponsePtr;
typedef boost::shared_ptr< ::qt_ground_station::SetHomeResponse const> SetHomeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_ground_station::SetHomeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_ground_station::SetHomeResponse_<ContainerAllocator1> & lhs, const ::qt_ground_station::SetHomeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.homeset_ok == rhs.homeset_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_ground_station::SetHomeResponse_<ContainerAllocator1> & lhs, const ::qt_ground_station::SetHomeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_ground_station

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56df5d8d0d1d06d2d92fe33cf4e8fff3";
  }

  static const char* value(const ::qt_ground_station::SetHomeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56df5d8d0d1d06d2ULL;
  static const uint64_t static_value2 = 0xd92fe33cf4e8fff3ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_ground_station/SetHomeResponse";
  }

  static const char* value(const ::qt_ground_station::SetHomeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  homeset_ok\n"
"\n"
;
  }

  static const char* value(const ::qt_ground_station::SetHomeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.homeset_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHomeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_ground_station::SetHomeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_ground_station::SetHomeResponse_<ContainerAllocator>& v)
  {
    s << indent << "homeset_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.homeset_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_SETHOMERESPONSE_H
