// Generated by gencpp from file qt_ground_station/SetHomeRequest.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_SETHOMEREQUEST_H
#define QT_GROUND_STATION_MESSAGE_SETHOMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_ground_station
{
template <class ContainerAllocator>
struct SetHomeRequest_
{
  typedef SetHomeRequest_<ContainerAllocator> Type;

  SetHomeRequest_()
    : longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)  {
    }
  SetHomeRequest_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHomeRequest_

typedef ::qt_ground_station::SetHomeRequest_<std::allocator<void> > SetHomeRequest;

typedef boost::shared_ptr< ::qt_ground_station::SetHomeRequest > SetHomeRequestPtr;
typedef boost::shared_ptr< ::qt_ground_station::SetHomeRequest const> SetHomeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_ground_station::SetHomeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_ground_station::SetHomeRequest_<ContainerAllocator1> & lhs, const ::qt_ground_station::SetHomeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_ground_station::SetHomeRequest_<ContainerAllocator1> & lhs, const ::qt_ground_station::SetHomeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_ground_station

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd1a22c4072a7707b77e062802e030ff";
  }

  static const char* value(const ::qt_ground_station::SetHomeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd1a22c4072a7707ULL;
  static const uint64_t static_value2 = 0xb77e062802e030ffULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_ground_station/SetHomeRequest";
  }

  static const char* value(const ::qt_ground_station::SetHomeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 longitude \n"
"float32 latitude\n"
"float32 altitude\n"
;
  }

  static const char* value(const ::qt_ground_station::SetHomeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHomeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_ground_station::SetHomeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_ground_station::SetHomeRequest_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_SETHOMEREQUEST_H
