// Generated by gencpp from file qt_ground_station/SinglePayloadAction.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_SINGLEPAYLOADACTION_H
#define QT_GROUND_STATION_MESSAGE_SINGLEPAYLOADACTION_H

#include <ros/service_traits.h>


#include <qt_ground_station/SinglePayloadActionRequest.h>
#include <qt_ground_station/SinglePayloadActionResponse.h>


namespace qt_ground_station
{

struct SinglePayloadAction
{

typedef SinglePayloadActionRequest Request;
typedef SinglePayloadActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SinglePayloadAction
} // namespace qt_ground_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_ground_station::SinglePayloadAction > {
  static const char* value()
  {
    return "901dfe89bb4f4622133561aed17b3eb7";
  }

  static const char* value(const ::qt_ground_station::SinglePayloadAction&) { return value(); }
};

template<>
struct DataType< ::qt_ground_station::SinglePayloadAction > {
  static const char* value()
  {
    return "qt_ground_station/SinglePayloadAction";
  }

  static const char* value(const ::qt_ground_station::SinglePayloadAction&) { return value(); }
};


// service_traits::MD5Sum< ::qt_ground_station::SinglePayloadActionRequest> should match
// service_traits::MD5Sum< ::qt_ground_station::SinglePayloadAction >
template<>
struct MD5Sum< ::qt_ground_station::SinglePayloadActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::SinglePayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::SinglePayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::SinglePayloadActionRequest> should match
// service_traits::DataType< ::qt_ground_station::SinglePayloadAction >
template<>
struct DataType< ::qt_ground_station::SinglePayloadActionRequest>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::SinglePayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::SinglePayloadActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_ground_station::SinglePayloadActionResponse> should match
// service_traits::MD5Sum< ::qt_ground_station::SinglePayloadAction >
template<>
struct MD5Sum< ::qt_ground_station::SinglePayloadActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_ground_station::SinglePayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::SinglePayloadActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_ground_station::SinglePayloadActionResponse> should match
// service_traits::DataType< ::qt_ground_station::SinglePayloadAction >
template<>
struct DataType< ::qt_ground_station::SinglePayloadActionResponse>
{
  static const char* value()
  {
    return DataType< ::qt_ground_station::SinglePayloadAction >::value();
  }
  static const char* value(const ::qt_ground_station::SinglePayloadActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_SINGLEPAYLOADACTION_H
