// Generated by gencpp from file qt_ground_station/SinglePayloadActionRequest.msg
// DO NOT EDIT!


#ifndef QT_GROUND_STATION_MESSAGE_SINGLEPAYLOADACTIONREQUEST_H
#define QT_GROUND_STATION_MESSAGE_SINGLEPAYLOADACTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_ground_station
{
template <class ContainerAllocator>
struct SinglePayloadActionRequest_
{
  typedef SinglePayloadActionRequest_<ContainerAllocator> Type;

  SinglePayloadActionRequest_()
    : perform_action(false)
    , action_type(0)  {
    }
  SinglePayloadActionRequest_(const ContainerAllocator& _alloc)
    : perform_action(false)
    , action_type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _perform_action_type;
  _perform_action_type perform_action;

   typedef int32_t _action_type_type;
  _action_type_type action_type;





  typedef boost::shared_ptr< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SinglePayloadActionRequest_

typedef ::qt_ground_station::SinglePayloadActionRequest_<std::allocator<void> > SinglePayloadActionRequest;

typedef boost::shared_ptr< ::qt_ground_station::SinglePayloadActionRequest > SinglePayloadActionRequestPtr;
typedef boost::shared_ptr< ::qt_ground_station::SinglePayloadActionRequest const> SinglePayloadActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator1> & lhs, const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.perform_action == rhs.perform_action &&
    lhs.action_type == rhs.action_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator1> & lhs, const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_ground_station

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "715e569e860f60215e794bdade55e91c";
  }

  static const char* value(const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x715e569e860f6021ULL;
  static const uint64_t static_value2 = 0x5e794bdade55e91cULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_ground_station/SinglePayloadActionRequest";
  }

  static const char* value(const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool perform_action\n"
"int32 action_type\n"
;
  }

  static const char* value(const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.perform_action);
      stream.next(m.action_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SinglePayloadActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_ground_station::SinglePayloadActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "perform_action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.perform_action);
    s << indent << "action_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_GROUND_STATION_MESSAGE_SINGLEPAYLOADACTIONREQUEST_H
